### PR TITLE
Cloudlets default to cloning with https

### LINKED ISSUE #126: As a Stewie without a Github account, I want to be able to install cloudlets
Currently it pulls as git@github.com (to setup remotes), but if the user does not have a Github account, or does not have it setup in, say, Cygwin, this fails with a permission denied error.

### PR DESCRIPTION
**Pull request by agperson**
A new option (specific to the registry/GitHub) lets users clone via SSH
instead.  Fixes #126.

### CODE REVIEW

**Comment by agperson** [comment]
Merged changes from master so build should pass.

**Comment by tfhartmann** [comment]
Hmmm did a bug seep in?

``` Shell
======================================================================
ERROR: test_nepho_cloudlet_upgrade (tests.cloudlet_test.a_TestNephoCloudlet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alaric/Projects/nepho/tests/cloudlet_test.py", line 78, in test_nepho_cloudlet_upgrade
    app.run()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/foundation.py", line 493, in run
    self.controller._dispatch()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 448, in _dispatch
    func()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 454, in _dispatch
    func()
  File "/Users/alaric/Projects/nepho/nepho/cli/cloudlet.py", line 179, in update
    c.update()
  File "/Users/alaric/Projects/nepho/nepho/core/cloudlet.py", line 101, in update
    repo.submodule_update()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 267, in submodule_update
    return RootModule(self).update(*args, **kwargs)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/objects/submodule/root.py", line 295, in update
    progress=progress, dry_run=dry_run)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/objects/submodule/base.py", line 386, in update
    mrepo = git.Repo.clone_from(self.url, module_path, n=True)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 739, in clone_from
    return cls._clone(Git(os.getcwd()), url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 691, in _clone
    finalize_process(proc)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/remote.py", line 64, in finalize_process
    proc.wait()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/cmd.py", line 100, in wait
    raise GitCommandError(self.args, status, self.proc.stderr.read())
GitCommandError: 'git clone -n -v git@github.com:cloudlets/aws-template-library.git /Users/alaric/.nepho/cloudlets/nepho-example/resources/common/aws' returned exit status 128: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

-------------------- >> begin captured stdout << ---------------------
Updating cloudlet: /Users/alaric/.nepho/cloudlets/nepho-example

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
```

**Comment by agperson** [comment]
No, the switch to HTTPS was intentional for better cross-platform support.  There is an (undocumented) config option that uses git@ instead of https://.  Is the problem that the submodule is using git rather than HTTPS?
~Danny

## 

Daniel Silverman zeno@agblog.com
"I'd take the awe of understanding over the awe of ignorance any day." - Douglas Adams
From: Tim Hartmann Tim Hartmann
Reply: huit/nepho reply@reply.github.com
Date: November 20, 2013 at 4:05:35 PM
To: huit/nepho nepho@noreply.github.com
Subject:  Re: [nepho] Cloudlets default to cloning with https (#127)  
Hmmm did a bug seep in?

# 

## ERROR: test_nepho_cloudlet_upgrade (tests.cloudlet_test.a_TestNephoCloudlet)

Traceback (most recent call last):
  File "/Users/alaric/Projects/nepho/tests/cloudlet_test.py", line 78, in test_nepho_cloudlet_upgrade
    app.run()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/foundation.py", line 493, in run
    self.controller._dispatch()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 448, in _dispatch
    func()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/cement-2.1.4.dev20131029203905-py2.7.egg/cement/core/controller.py", line 454, in _dispatch
    func()
  File "/Users/alaric/Projects/nepho/nepho/cli/cloudlet.py", line 179, in update
    c.update()
  File "/Users/alaric/Projects/nepho/nepho/core/cloudlet.py", line 101, in update
    repo.submodule_update()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 267, in submodule_update
    return RootModule(self).update(_args, *_kwargs)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/objects/submodule/root.py", line 295, in update
    progress=progress, dry_run=dry_run)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/objects/submodule/base.py", line 386, in update
    mrepo = git.Repo.clone_from(self.url, module_path, n=True)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 739, in clone_from
    return cls._clone(Git(os.getcwd()), url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 691, in _clone
    finalize_process(proc)
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/remote.py", line 64, in finalize_process
    proc.wait()
  File "/Users/alaric/.virtualenvs/nepho/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/cmd.py", line 100, in wait
    raise GitCommandError(self.args, status, self.proc.stderr.read())
GitCommandError: 'git clone -n -v git@github.com:cloudlets/aws-template-library.git /Users/alaric/.nepho/cloudlets/nepho-example/resources/common/aws' returned exit status 128: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

-------------------- >> begin captured stdout << ---------------------
Updating cloudlet: /Users/alaric/.nepho/cloudlets/nepho-example

--------------------- >> end captured stdout << ----------------------

---

**Comment by tfhartmann** [comment]
yeah, I think thats whats happening.  My issue cleared up locally when I re-added my pubkey to github, but from the output it looks to me like the submodule is using ssh

**Pull request merged**
