### PR TITLE
Validate cloudlet registry YAML

### LINKED ISSUE #153: do not store invalid YAML in the registry
```
$ cat ~/.nepho/cache/registry.yaml

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Connection timed out</title>
  </head>
  <body>
    <h1>Error 503 Connection timed out</h1>
    <p>Connection timed out</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 3186682312</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

that seems suboptimal.  it causes nasty tracebacks with nepho complaining about not being able to parse the YAML.

arguably we should address this problem by capturing whatever registry data gets downloaded, trying to load it, and trapping `YAMLError`s.

### PR DESCRIPTION
**Pull request by hakamadare**
This commit adds a couple pieces of functionality:
1. Rather than accepting whatever the GitHub page gives us, use
   `yaml.safe_load()` and `yaml.safe_dump()` to make sure that we're
   storing valid YAML in the registry.
2. In the event that we try to load registry data and receive invalid
   YAML, throw an informative error message and clear the registry cache.

Fixes #153

### CODE REVIEW

**Comment by tfhartmann** [comment]
@hakamadare Failed Travis, looks like a formatting thing

**Comment by agperson** [comment]
Just use load, safe_load is not Python 3 compatible.

On Tuesday, November 19, 2013, Tim Hartmann wrote:

> @hakamadare https://github.com/hakamadare Failed Travis, looks like a
> formatting thing
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/huit/nepho/pull/158#issuecomment-28843267
> .

## 

Daniel Silverman zeno@agblog.com
"I'd take the awe of understanding over the awe of ignorance any day." -
Douglas Adams

**Comment by agperson** [comment]
I'm sorry @hakamadare I had a brain fart.  You were right to use safe_load.

**Comment by hakamadare** [comment]
it's all good :shipit:

**Pull request merged**
